// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List blog posts (writing, podcast, video, external link) from the Eran Bert site. Returns id, slug, title, description, post_type, status, published_at.",
  inputSchema: {
    status: z.enum(["published", "draft", "all"]).optional().describe("Filter by status. Defaults to 'published'."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    let q = sb.from("blog_posts").select("id,slug,title,description,post_type,status,published_at,cover_image_url,external_url,embed_url").order("published_at", { ascending: false }).limit(limit ?? 50);
    if (!status || status === "published") q = q.eq("status", "published");
    else if (status === "draft") q = q.eq("status", "draft");
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { posts: data } };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch a single blog post by slug, including its full content (markdown).",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("The blog post slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("blog_posts").select("*").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { post: data } };
  }
});

// src/lib/mcp/tools/list-programs.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_programs_default = defineTool3({
  name: "list_programs",
  title: "List programs",
  description: "List training programs offered by Eran Bert (title, short/full description, image, external registration URL).",
  inputSchema: {
    status: z3.enum(["active", "hidden", "all"]).optional().describe("Filter by status. Defaults to 'active'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser3(ctx);
    let q = sb.from("programs").select("*").order("sort_order", { ascending: true });
    if (!status || status === "active") q = q.eq("status", "active");
    else if (status === "hidden") q = q.eq("status", "hidden");
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { programs: data } };
  }
});

// src/lib/mcp/tools/get-site-content.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_site_content_default = defineTool4({
  name: "get_site_content",
  title: "Get site content",
  description: "Get the bilingual site content strings (Hebrew and English) as key/value entries. Useful for reviewing or referencing published copy on the Eran Bert site.",
  inputSchema: {
    key_prefix: z4.string().trim().optional().describe("Optional key prefix filter, e.g. 'hero.' or 'philosophy.'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ key_prefix }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser4(ctx);
    let q = sb.from("site_content").select("*");
    if (key_prefix) q = q.like("key", `${key_prefix}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { entries: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ixavhqmxhfwayimlyaee";
var mcp_default = defineMcp({
  name: "eran-bert-mcp",
  title: "Eran Bert",
  version: "0.1.0",
  instructions: "Read-only tools for the Eran Bert site: browse published blog posts (writing, podcast, video, external links), read a single post's full markdown by slug, list training programs, and fetch bilingual site copy. Callers act as their signed-in user under the app's row-level security policies.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_blog_posts_default, get_blog_post_default, list_programs_default, get_site_content_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
